version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: hanzohanic/udagram-proxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: hanzohanic/udagram-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: hanzohanic/udagram-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: hanzohanic/udagram-front:local